create_character:
  description: >
    Create a new character for the story.
    
    The character should be developed using the Hero's Journey framework.
    The character should have a clear goal and motivation.
    The character should have a backstory that fits into the world of the story.
  expected_output: >
    A new character with a name, description, goal, motivation, and backstory.
  agent: creative_writer


develop_character:
  description: >
    Develop a new story event for the characters timeline.
  expected_output: >
    The story event should involve any of these characters:


    {characters}


    This is a synopsis of previous events:


    {synopsis}


    The current stage in Joseph Campbell's Hero's Journey is: {stage} 
    A detailed description of the new story event that evolves from the characters' choices.
    The description should have details about location, time, and other characters involved.
  agent: creative_writer

develop_environment:
  description: >
    Develop a new story event that does not involve the characters directly.
  expected_output: >
    This is the synopsis of the story so far:

    {synopsis}

    Use Joseph Campbell's Hero's Journey as a blueprint for the story.
    The current stage is the Hero's Journey framework is: {stage} 
    The event description should have details about locations and characters involved in the event.
    Use a narrative style in your writing.
    Events do not need to involve the characters directly.
  agent: creative_writer


consistency_check:
  description: >
    Check the consistency of new story events with previous events.
  expected_output: >
    The plot should follow the stages of the hero's journey and be consistent with the established characters
    personality and past events.

    This is the synopsis of the story so far:

    {synopsis}

    The output should be a short concise repor on the consistency of the new story events with the previous events.
    Mention any inconsistencies and suggest corrections if needed.
  agent: consistency_checker

stage_writeup:
  description: >
    Finalize the {stage} stage of the story. Once finalized, the stage will be added to the synopsis.
    
  expected_output: >
    This is the synopsis of the story you must continue from:

    {synopsis}

    Finalize the next stage of the story: {stage}
    
    Avoid any references to the Hero's Journey stages in the synopsis.
    Do not reference the Hero's Journey in the synopsis as it might confuse the final audience.
    A list of events that are part of the {stage} stage of the story and the names of the characters involved in the events.
    Chapter title should not be the same as the stage title, use metaphores or allegories instead.
    A synopsis of the events in narrative form.
    The synopsis should hide any references to the Hero's Journey stages by using allegorical language.
  agent: creative_writer